const ACTION_TYPES = {
  CREATE_HERO_REQUEST: "CREATE_HERO_REQUEST",
  CREATE_HERO_SUCCESS: "CREATE_HERO_SUCCESS",
  CREATE_HERO_ERROR: "CREATE_HERO_ERROR",

  GET_HEROES_REQUEST: "GET_HEROES_REQUEST",
  GET_HEROES_SUCCESS: "GET_HEROES_SUCCESS",
  GET_HEROES_ERROR: "GET_HEROES_ERROR",

  DELETE_HERO_REQUEST: "DELETE_HERO_REQUEST",
  DELETE_HERO_SUCCESS: "DELETE_HERO_SUCCESS",
  DELETE_HERO_ERROR: "DELETE_HERO_ERROR"
}

export default ACTION_TYPES;