const ACTION_TYPES = {
  CREATE_HERO_REQUEST: "CREATE_HERO_REQUEST",
  CREATE_HERO_SUCCESS: "CREATE_HERO_SUCCESS",
  CREATE_HERO_ERROR: "CREATE_HERO_ERROR",

  GET_HEROES_REQUEST: "GET_HEROES_REQUEST",
  GET_HEROES_SUCCESS: "GET_HEROES_SUCCESS",
  GET_HEROES_ERROR: "GET_HEROES_ERROR",

  DELETE_HERO_REQUEST: "DELETE_HERO_REQUEST",
  DELETE_HERO_SUCCESS: "DELETE_HERO_SUCCESS",
  DELETE_HERO_ERROR: "DELETE_HERO_ERROR",

  UPDATE_HERO_REQUEST: "UPDATE_HERO_REQUEST",
  UPDATE_HERO_SUCCESS: "UPDATE_HERO_SUCCESS",
  UPDATE_HERO_ERROR: "UPDATE_HERO_ERROR",
  
  CREATE_SUPER_POWER_REQUEST: "CREATE_SUPER_POWER_REQUEST",
  CREATE_SUPER_POWER_SUCCESS: "CREATE_SUPER_POWER_SUCCESS",
  CREATE_SUPER_POWER_ERROR: "CREATE_SUPER_POWER_ERROR",

  DELETE_SUPER_POWER_REQUEST: "DELETE_SUPER_POWER_REQUEST",
  DELETE_SUPER_POWER_SUCCESS: "DELETE_SUPER_POWER_SUCCESS",
  DELETE_SUPER_POWER_ERROR: "DELETE_SUPER_POWER_ERROR",

  CREATE_SUPER_HERO_IMG_REQUEST: "CREATE_SUPER_HERO_IMG_REQUEST",
  CREATE_SUPER_HERO_IMG_SUCCESS: "CREATE_SUPER_HERO_IMG_SUCCESS",
  CREATE_SUPER_HERO_IMG_ERROR: "CREATE_SUPER_HERO_IMG_ERROR"
}

export default ACTION_TYPES;